name: Branch
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Run Audit fix
        run: |
          npm_config_yes=true npx yarn-audit-fix
          npm audit fix --force

      - name: Build
        run: yarn build

      - name: Commit and push
        uses: EndBug/add-and-commit@v9 
        with:
          add: '*'
          message: Auto compile