name: Branch
on:
  push:
    branches:
      - activity-report
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Commit and push
        uses: EndBug/add-and-commit@v9 
        with:
          add: '*'
          message: Auto compile