name: Branch
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Install
        run: yarn install

      - name: Run Audit fix
        run: |
          npm cache verify
          npm_config_yes=true npx yarn-audit-fix
          npm i --package-lock-only
          npm audit fix --force

      - name: Build
        run: |
          NODE_OPTIONS=--openssl-legacy-provider yarn build
          rm -rf node_modules


#      - name: Semantic Release
#        uses: wow-actions/release-github-action@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v9 
        with:
          add: '-f . dist'
          message: Auto compile
